### ISSUE TITLE
1.0.3.3 - Forced UPD_DB notification

### ISSUE THREAD

**Issue by VAM-Kitten** [feelfar/varManager#11]
Since 1.0.3.3 there has been a VAR database consistency checkup and the application does not allow me to ignore this message:

![UnorganizedVARS](https://user-images.githubusercontent.com/95571452/173775493-448542d7-794a-4d84-8c56-0fd1043ae5bd.png)

The problem is that every time I update my VAR database, I put a few most important VARS in the root AddonPackages folder to have a quick access to them:

![IMPORTANT_VARS](https://user-images.githubusercontent.com/95571452/173775733-3a57bde6-90ca-4a91-95ed-197a671a67e8.png)

Unfortunately, your application detects those VARS and shows this notification that I can't skip. If I click UPD_DB, I lose those few VARS from the main directory.

Possible solutions:

1. Please add "Do not check the DB consistency" option in the settings
2. Please add "Ignore" or "Always Ignore" button to this notification.

Thanks!

**Comment by feelfar** [comment]
Please try this
1.upd db
2.Install the  files
3.Move the  links to these  files from __varlink__

**Comment by feelfar** [comment]
v1.0.4.0 has been removed it.
