### ISSUE TITLE
1.0.3.3 Microsoft.ACE.OLEDB.12.0

### ISSUE THREAD

**Issue by thebrokenfacade** [feelfar/varManager#12]
In both 1.0.3.1 and 1.0.3.3 I get an error when the application is started. 

Some research yields that the issue may be a missing dependency or an issue with x86 code running on a x64 system.
https://docs.microsoft.com/en-us/previous-versions/troubleshoot/winautomation/support-tips/databases/ace-oledb-12-0-provider-not-registered-on-local-machine
![error](https://user-images.githubusercontent.com/37705420/176973951-79c171df-221f-4a91-aace-8ee39bc89ada.JPG)

**Comment by VAM-Kitten** [comment]
I got the same error on a fresh Windows system. I remember that Installing components from that link fixed the problem.

**Comment by feelfar** [comment]
There is a link on your post
https://www.microsoft.com/en-us/download/details.aspx?id=54920
download accessdatabaseengine_X64.exe and install

**Comment by thebrokenfacade** [comment]
Thanks for the quick replies. 

I tried both the options from the link that I provided. Neither of them worked for me on a fresh install of windows 10. Maybe in my region the post links to different urls?
- [Microsoft Data Access Components (MDAC) 2.8 SP1]
- https://www.microsoft.com/download/details.aspx?id=5793
- [Microsoft Access Database Engine 2010 Redistributable]
- https://www.microsoft.com/download/details.aspx?id=13255

Following feelfar's instruction did work. I downloaded "accessdatabaseengine_X64.exe" from https://www.microsoft.com/en-us/download/details.aspx?id=54920 and installed it. I then restarted my system and everything seems to work now. For those trying to follow along, you need to install Microsoft Access Database Engine **2016** Redistributable.
