### ISSUE TITLE
Access denied and version number mismatch

### ISSUE THREAD

**Issue by VAM-Kitten** [feelfar/varManager#6]
Hi

**Issue 1:**
When I launch version 1.0.2.3, I get Access Denied error:

<img width="330" alt="VarManager_1023_error" src="https://user-images.githubusercontent.com/95571452/166437634-a8f9c7bc-1b7f-4b96-ae3a-580ea31d1b73.png">

even if I try to run it as an administrator. All folders security are set to full control for Everyone.

Version 1.0.1.1 was and is still working fine.

**Issue 2:**

Although I've downloaded version 1.0.2.3, it still shows 1.0.2.2.

<img width="180" alt="VARversion" src="https://user-images.githubusercontent.com/95571452/166437665-0b181335-97ab-4c8d-a081-b37385c0c066.png">

Thanks for all your hard work!

**EDIT:** It seems that there was something wrong with the release file. After compiling the source, both issues (access problem and version number) have disappeared, so this issue is fixed for me.

**Comment by feelfar** [comment]
Forgive me for taking so long to reply, it should be my mistake, thanks for your support
