### ISSUE TITLE
Missing VAR reported as Access Denied

### ISSUE THREAD

**Issue by VAM-Kitten** [feelfar/varManager#7]
First of all, congrats on version 1.0.3.0, it's working great. The only problem I have is when I use "SAVES JSONfile" option to scan my scenes/appearances for dependencies. It's a very useful option!

So the problem is - if there is a reference in the JSON file to a specific version of VAR file and I do not have that version of VAR in my repository, but I do have later versions, after the scanning, when I linked that missing version to a later version and click OK, I get the error (see attached).

<img width="1012" alt="VarManagerLinkError" src="https://user-images.githubusercontent.com/95571452/171983160-59200440-8158-4703-b3d9-2e016264f23a.png">

At first I thought it was really a problem with access rights, but it was not. I hope you will fix it in the next version.

EDIT: I've found out that your tool is actually working, it DOES link the previous version of VAR to the latest version and puts a link in the MissingVarLink folder. So this error appears to be an annoyance. I will be testing it further.

Overall, your tool is a must for every VAM user, so thank you for your hard work!

**Comment by feelfar** [comment]
Forgive my English level, I can't reproduce this error on my machine, but I seem to have found the code that triggers the error and modified it, I hope you will test it again and give me feedback

**Comment by VAM-Kitten** [comment]
I've tested it and the error does not appear anymore.
As for your English, I don't see anything wrong with it, there is nothing to forgive ;)

**Comment by feelfar** [comment]
Google translate, DeepL...😂
